# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000  # Binding to 0.0.0.0 for accessibility
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"

version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=instagram_clone
      - DB_USER=myuser
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: instagram_clone
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:



